/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedStoriesRouteImport } from './routes/_authenticated/stories'
import { Route as UnauthenticatedLoginRouteImport } from './routes/_unauthenticated/login'
import { Route as UnauthenticatedSignupRouteImport } from './routes/_unauthenticated/signup'
import { Route as AuthenticatedStoriesStoryIdRouteImport } from './routes/_authenticated/stories.$storyId'
import { Route as AuthenticatedStoriesNewRouteImport } from './routes/_authenticated/stories.new'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users.$userId'
import { Route as AuthenticatedStoriesStoryIdEditRouteImport } from './routes/_authenticated/stories.$storyId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoriesRoute = AuthenticatedStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UnauthenticatedLoginRoute = UnauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const UnauthenticatedSignupRoute = UnauthenticatedSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const AuthenticatedStoriesStoryIdRoute =
  AuthenticatedStoriesStoryIdRouteImport.update({
    id: '/$storyId',
    path: '/$storyId',
    getParentRoute: () => AuthenticatedStoriesRoute,
  } as any)
const AuthenticatedStoriesNewRoute = AuthenticatedStoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedStoriesRoute,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStoriesStoryIdEditRoute =
  AuthenticatedStoriesStoryIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedStoriesStoryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/me': typeof AuthenticatedMeRoute
  '/stories': typeof AuthenticatedStoriesRouteWithChildren
  '/login': typeof UnauthenticatedLoginRoute
  '/signup': typeof UnauthenticatedSignupRoute
  '/stories/$storyId': typeof AuthenticatedStoriesStoryIdRouteWithChildren
  '/stories/new': typeof AuthenticatedStoriesNewRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/stories/$storyId/edit': typeof AuthenticatedStoriesStoryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/me': typeof AuthenticatedMeRoute
  '/stories': typeof AuthenticatedStoriesRouteWithChildren
  '/login': typeof UnauthenticatedLoginRoute
  '/signup': typeof UnauthenticatedSignupRoute
  '/stories/$storyId': typeof AuthenticatedStoriesStoryIdRouteWithChildren
  '/stories/new': typeof AuthenticatedStoriesNewRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/stories/$storyId/edit': typeof AuthenticatedStoriesStoryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/stories': typeof AuthenticatedStoriesRouteWithChildren
  '/_unauthenticated/login': typeof UnauthenticatedLoginRoute
  '/_unauthenticated/signup': typeof UnauthenticatedSignupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/stories/$storyId': typeof AuthenticatedStoriesStoryIdRouteWithChildren
  '/_authenticated/stories/new': typeof AuthenticatedStoriesNewRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/stories/$storyId/edit': typeof AuthenticatedStoriesStoryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/me'
    | '/stories'
    | '/login'
    | '/signup'
    | '/stories/$storyId'
    | '/stories/new'
    | '/users/$userId'
    | '/stories/$storyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/me'
    | '/stories'
    | '/login'
    | '/signup'
    | '/stories/$storyId'
    | '/stories/new'
    | '/users/$userId'
    | '/stories/$storyId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/me'
    | '/_authenticated/stories'
    | '/_unauthenticated/login'
    | '/_unauthenticated/signup'
    | '/_authenticated/'
    | '/_authenticated/stories/$storyId'
    | '/_authenticated/stories/new'
    | '/_authenticated/users/$userId'
    | '/_authenticated/stories/$storyId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stories': {
      id: '/_authenticated/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof AuthenticatedStoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/login': {
      id: '/_unauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/signup': {
      id: '/_unauthenticated/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof UnauthenticatedSignupRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/stories/$storyId': {
      id: '/_authenticated/stories/$storyId'
      path: '/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof AuthenticatedStoriesStoryIdRouteImport
      parentRoute: typeof AuthenticatedStoriesRoute
    }
    '/_authenticated/stories/new': {
      id: '/_authenticated/stories/new'
      path: '/new'
      fullPath: '/stories/new'
      preLoaderRoute: typeof AuthenticatedStoriesNewRouteImport
      parentRoute: typeof AuthenticatedStoriesRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stories/$storyId/edit': {
      id: '/_authenticated/stories/$storyId/edit'
      path: '/edit'
      fullPath: '/stories/$storyId/edit'
      preLoaderRoute: typeof AuthenticatedStoriesStoryIdEditRouteImport
      parentRoute: typeof AuthenticatedStoriesStoryIdRoute
    }
  }
}

interface AuthenticatedStoriesStoryIdRouteChildren {
  AuthenticatedStoriesStoryIdEditRoute: typeof AuthenticatedStoriesStoryIdEditRoute
}

const AuthenticatedStoriesStoryIdRouteChildren: AuthenticatedStoriesStoryIdRouteChildren =
  {
    AuthenticatedStoriesStoryIdEditRoute: AuthenticatedStoriesStoryIdEditRoute,
  }

const AuthenticatedStoriesStoryIdRouteWithChildren =
  AuthenticatedStoriesStoryIdRoute._addFileChildren(
    AuthenticatedStoriesStoryIdRouteChildren,
  )

interface AuthenticatedStoriesRouteChildren {
  AuthenticatedStoriesStoryIdRoute: typeof AuthenticatedStoriesStoryIdRouteWithChildren
  AuthenticatedStoriesNewRoute: typeof AuthenticatedStoriesNewRoute
}

const AuthenticatedStoriesRouteChildren: AuthenticatedStoriesRouteChildren = {
  AuthenticatedStoriesStoryIdRoute:
    AuthenticatedStoriesStoryIdRouteWithChildren,
  AuthenticatedStoriesNewRoute: AuthenticatedStoriesNewRoute,
}

const AuthenticatedStoriesRouteWithChildren =
  AuthenticatedStoriesRoute._addFileChildren(AuthenticatedStoriesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedStoriesRoute: typeof AuthenticatedStoriesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedStoriesRoute: AuthenticatedStoriesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedLoginRoute: typeof UnauthenticatedLoginRoute
  UnauthenticatedSignupRoute: typeof UnauthenticatedSignupRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedLoginRoute: UnauthenticatedLoginRoute,
  UnauthenticatedSignupRoute: UnauthenticatedSignupRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
